# Publishing {#sec-publishing}

As detailed in the original project description to the Novo Nordisk Foundation
(<https://dp-next.github.io/>) and Section 12 of the collaboration agreement, we
aim to work, collaborate, and publish following the principles of open and
reproducible science.

Briefly, the collaboration agreement states that the [Steering
Committee](https://dp-next.github.io/who-we-are.html) is responsible for
outlining and implementing the project's publication strategy. The main aims of
this strategy are:

- To jointly publish positive, negative, and inconclusive results in
  international peer-reviewed scientific journals.
- To work according to open and reproducible research practices.

To achieve the "open" part of the aim, we'll publish scientific output in
journals as Open Access publications, with a strong preference for:

- The Green Open Access format (meaning to publish as a pre-print in an open
  archive such as [Zenodo](https://zenodo.org) or bioRxiv).
- Publication agreements that do not require the transfer of copyright to
  publishers.
- Publishing under a [Creative Commons Attribution
  (CC-BY)](https://creativecommons.org/licenses/by/4.0/) license.

::: callout-note
In case of any fundamental discrepancy or conflict between this page and the
collaboration agreement, the text of the collaboration agreement has precedence.
If any substantial deviations from this guide are needed for a particular
research project, the authors should justify the deviations and request approval
to proceed from the Steering Committee.
:::

So, how do we put this strategy into practice? When a scientific output is ready
to be disseminated, either "informally" (in archives like Zenodo or at
conferences) or "formally" in journals, in DP-Next we follow a specific path for
formal or informal publishing.

## Formally disseminate

This section is only relevant for 'new results', which means any results that
have not yet been formally published in a peer-reviewed journal. Results
included in a conference abstract or presentation are still considered new
results until they are formally published.

When your research project has been reviewed by coauthors, is ready to be
submitted to be formally published in an academic journal, you need to inform
the management group that your project is ready.

You can do that either by creating an issue on the WP1-Management repo or by
sending a message in the "General" Discord channel by pinging the management
group with "\@admin". An overview of this process is shown below in
@fig-publication-steps.

```{mermaid}
%%| label: fig-publication-steps
%%| fig-cap: >-
%%|   Steps to follow for formally publishing scientific output during the life
%%|   cycle of a DP-Next project. The rounded boxes in orange are tasks you are
%%|   responsible for doing. The rectangular ones in light blue are for the
%%|   committee members to do.
%%| fig-alt: >-
%%|   Boxes and arrows indicating the flow of tasks from preparation to
%%|   publication. The boxes are colored according to whether they are the
%%|   responsibility of the authors or the committee members. These tasks are
%%|   visual representations of the text below.

graph LR
    subgraph S1["Output ready"]
      direction TB
      ready("Finished output<br>ready for review"):::yours
      inform_coauthors("Inform coauthors"):::yours
      inform_management("Inform management"):::yours
      ready --> inform_coauthors --> inform_management
    end

    subgraph S2["Review and archive"]
      review["Review output"]:::ours
      respond("Respond and<br>revise (if needed)"):::yours
      approve["Output approved"]:::ours
      zenodo["Upload output<br>to Zenodo<br>(e.g. preprint)"]:::ours
      github["GitHub repository<br>to Zenodo"]:::ours
      review --> respond --> review
      respond --> approve --> zenodo --> github
    end

    subgraph S3["Formally publish"]
      journal("Submit output<br>to journal"):::yours
      track("Track review status,<br>updates and acceptance"):::yours
      inform_end("Update everyone<br>via Discord"):::yours
      update_metadata("Update metadata<br>in 'dp-next.yaml'"):::yours
      journal --> track --> inform_end --> update_metadata
    end

    S1 -.-> S2 -.-> S3

    style S1 fill:#FFFFFF, color:#000000
    style S2 fill:#FFFFFF, color:#000000
    style S3 fill:#FFFFFF, color:#000000
    classDef ours fill:#ADD8E6;
    classDef yours fill:#FFA07A;
```

You should inform us (the management group) at least two weeks before the
intended submission date or deadline. We'll inform you on whether we agree or
disagree with the publication as soon as possible and within the two weeks. No
response from us can be regarded as agreement and you can continue with the
submission.

We'll notify the full Steering Committee, who may assign some of its members to
review and approve on the committee's behalf. The Steering Committee will only
disagree with the submission of a paper or abstract at this stage if it seems to
be premature or is repetition of previous work. Disagreement can also happen if
you haven't followed most of the process described in this guide, e.g. no GitHub
repository, no approved synopsis, no protocol.

When someone starts reviewing your project, you should respond as quickly as
possible to any review comments and to make updates to the project and paper as
quickly as possible. After we've given approval, we'll archive the paper as a
pre-print to Zenodo and upload the GitHub repository to Zenodo to archive the
analysis code.

Once those tasks have been done, you can submit your paper to the journal. It's
now your responsibility to track the submission progress, respond to review
comments (including making changes to the paper in the GitHub repository), and
keep us updated on the status. Once the paper is published, you also need to
update the `dp-next.yaml` file in your repository.

## Informally disseminate

If you want to disseminate something that is generally about DP-Next or on
formally published results, you don't need approval from the Steering Committee.
However, we would still appreciate it if you kept us informed, via the Discord
channel or by making an issue on WP1-Management with details about the
dissemination activity.

Informal dissemination could include: keynotes, invited talks, press releases,
media appearances, podcasts, posts on social media, or outreach activities. In
general, these activities must not interfere with or weaken the opportunities
for formal academic publication of the study results.

As your project progresses, you'll likely produce various interim results and
materials. As far as possible, these should be kept in the project's GitHub
repository.

If you want to include preliminary or new results in lectures or seminars that
are outside of DP-Next, do so with great care. If you want to present new
results in small academic circles, please notify the management group before
giving the presentation by creating an issue in the research project's GitHub
(or in the WP1-Management repository).

You should ideally only disseminate new results through broader media or
outreach activities *after* disseminating the results in as a conference
abstract or presentation. In the case of a press release related to the
conference, you can prepare the dissemination beforehand under a time embargo
that coincides with the academic presentation of results. Before issuing any
press release, you should inform the management group via an issue on the
(private) WP1-Management repo. You should do this as early as possible. If you
need approval in less than 72 hours, send an e-mail to or call one of the
members of Steering Committee.
