# Start a new project {#sec-new-project}

If you are part of DP-Next (or not), you'll be working on research projects,
likely using data collected during DP-Next or from existing data (e.g.
ADDITION-PRO). This chapter describes what to do when starting a new project.
Below in @fig-new-project-steps is a visual summary of the steps to take, along
with descriptions afterwards that outline the steps in more detail.

```{mermaid}
%%| label: fig-new-project-steps
%%| fig-cap: |
%%|   Steps to take for starting a project within DP-Next. The rounded boxes in
%%|   orange are tasks you are responsible for doing. The rectangular ones in
%%|   light blue are for the managers ("us") to do.
%%| fig-alt: |
%%|   Boxes and arrows indicating the flow of tasks from creating an issue to
%%|   filling in the 'dp-next.yaml' file. The boxes are colored according to
%%|   whether they are the responsibility of the authors ("you") or the managers
%%|   ("us"). These tasks are visual representations of the text below.

graph TB
  A0("Review existing projects<br>for any overlap with your<br>potential project<br>(you)"):::yours
  A("Create GitHub<br>project proposal issue<br>(you)"):::yours
  B["Synopsis review<br>and approval<br>(us)"]:::ours
  C["Data agreement<br>(if required)<br>(us)"]:::ours
  D["Create GitHub<br>repository<br>(us)"]:::ours
  E("Complete TODOs in<br>'dp-next.yaml'<br>(you)"):::yours
  A0 --> A --> B --> C --> D --> E

  classDef ours fill:#ADD8E6;
  classDef yours fill:#FFA07A;
```

The requirements for preparing a DP-Next publication apply to both internal and
external researchers and should follow these steps:

<!-- TODO: Link to webpage that listed all research projects in DP-Next -->

<!-- TODO: May need to update link to project proposal, might be in a new repo. -->

<!-- TODO: Include link to design repo for naming of repos. -->

1. Before proposing a project, make sure that you aren't doing something that's
   already done or being worked on. If there is a current ongoing project that
   is similar to what you wanted to work on, you can request to collaborate on
   that project with those researchers.

2. If there is no other project that is similar to your project idea, you can
   propose the project. Create a new issue in the
   [WP1-Management](https://github.com/dp-next/WP1-Management) repo (private for
   now) and select the "Project proposal" issue template. Fill in the fields
   there, which we'll use to assess how relevant the project is within DP-Next.

3. Once you've created the issue, at least one member of the [Steering
   Committee](https://dp-next.github.io/who-we-are.html#sc) needs to review and
   approve it (usually either the principle investigator or the general
   coordinator). It is possible that someone may approve it, but later another
   committee member may request changes or give comments. If that happens, it is
   fairly easy to update the project. Once approved, someone with access
   permissions (e.g. in [WP1](https://dp-next.github.io/who-we-are.html#wp1))
   will create a GitHub repository for the project by using the DP-Next
   [template project](https://dp-next.github.io/template-project) and following
   our naming convention.

4. After the repository is created, you need to go through the repository and
   complete any TODO items, such as those found in the `TODO.md` file.
   Importantly, the TODO items in the `dp-next.yaml` file need to be filled. We
   use the information in this file to create an overview of the different
   projects going on in DP-Next.

::: callout-note
We expect that many new projects based on DP-Next data will be done by DP-Next
researchers. However, we also welcome collaborations with external researchers
(i.e. those who are not part of DP-Next), though these projects must include at
least one DP-Next member as coauthor so that projects follow our standards.
Projects can be stand-alone or part of a wider initiative, such as a PhD or
postdoc protocol.
:::

::: callout-warning
For investigators not covered by the DP-Next agreements (by institutional
affiliation to one of the Steno Diabetes Centres), a separate data agreement
must be signed if they require data access. This agreement must be in place
before any data access can be given.
:::
